Repository WebUI-Project-Based-07-nr/BackEnd, pull requests merged in 2024-08, with the labels that each got.

#71 Location service extended
  src/consts/location.js
  src/controllers/location.js
  src/routes/location.js
  src/services/location.js
  src/test/integration/controllers/location.spec.js
  src/test/unit/services/location.spec.js
  src/utils/location/location.js
Labels: Backend, feature, sprint 4

#68 Category Model
  src/consts/models.js
  src/docs/schemas/category/category.js
  src/middlewares/swagger.js
  src/models/category.js
Labels: Backend, feature, sprint 4

#80 Lesson model
  src/docs/schemas/lesson/lesson.js
  src/middlewares/swagger.js
  src/models/lesson.js
Labels: Backend, feature, sprint 5

#75 "Add category" endpoint
  src/controllers/category.js
  src/docs/schemas/category/create-category.js
  src/middlewares/swagger.js
  src/routes/category.js
  src/routes/index.js
  src/services/category.js
  src/test/integration/controllers/category.spec.js
  src/test/unit/services/category.spec.js
Labels: Backend, feature, sprint 4

#82 Integration of categorization and subject classification into offer system
  src/models/offer.js
  src/utils/offers/offerAggregateOptions.js
Labels: Backend, feature, sprint 5

#83 'Get Categories' endpoint
  src/controllers/category.js
  src/docs/schemas/category/get-categories.js
  src/middlewares/swagger.js
  src/routes/category.js
  src/routes/index.js
  src/services/category.js
  src/test/integration/controllers/category.spec.js
  src/test/unit/services/category.spec.js
Labels: Backend, feature, sprint 4

#93 added fix native language
  src/controllers/auth.js
  src/services/auth.js
  src/services/user.js
Labels: bug, sprint 5

#100 Get Image endpoint
  src/controllers/user.js
  src/routes/user.js
  src/services/image.js
Labels: Backend, feature, sprint 6

#102 #101 query update and role permissions
  src/controllers/subject.js
  src/routes/category.js
  src/routes/subjects.js
  src/utils/categories/categoriesAggregateOptions.js
Labels: Backend, feature

#104 Template Paths in Email Service
  src/services/email.js
Labels: Backend, feature, sprint 6

#96 Endpoints for Lesson
  src/consts/errors.js
  src/controllers/category.js
  src/controllers/lesson.js
  src/models/lesson.js
  src/routes/index.js
  src/routes/lesson.js
  src/services/lesson.js
  src/validation/services/lesson.js
Labels: Backend, feature, sprint 5

#107 fix category service create arguments
  src/services/category.js
Labels: bug, sprint 6

#94 Delete Subject endpoint
  src/controllers/subject.js
  src/routes/subjects.js
  src/services/subject.js
Labels: Backend, feature, sprint 6

#108 fix service creation
  src/services/category.js
Labels: bug

#88 Offer model validation
  src/models/offer.js
Labels: Backend, feature, sprint 5

#105 Fix failing tests
  .github/workflows/main.yaml
  src/controllers/auth.js
  src/routes/category.js
  src/routes/subjects.js
  src/services/auth.js
  src/services/category.js
  src/test/integration/controllers/auth.spec.js
  src/test/integration/controllers/category.spec.js
  src/test/integration/controllers/resourcesCategory.spec.js
  src/test/integration/services/auth.spec.js
  src/test/integration/services/question.spec.js
  src/test/integration/services/user.spec.js
  src/utils/testUserAuth.js
Labels: Backend, fix

#114 Fix imports
  src/routes/category.js
  src/routes/subjects.js
Labels: Backend, fix

#111 #110 move pipline to the separate file and added totalOffer
  src/controllers/subject.js
  src/utils/subjects/subjectsAggregateOptions.js
Labels: Backend, feature, sprint 6

#117 Adjusted Tests
  src/test/integration/controllers/category.spec.js
  src/test/integration/controllers/subject.spec.js
  src/test/unit/services/category.spec.js
Labels: Backend, fix

#109 Quiz Model and Endpoints
  src/consts/errors.js
  src/controllers/quiz.js
  src/docs/schemas/quiz/create-quiz.js
  src/docs/schemas/quiz/delete-quiz.js
  src/docs/schemas/quiz/get-quiz-by-id.js
  src/docs/schemas/quiz/get-quizzes.js
  src/docs/schemas/quiz/update-quiz.js
  src/middlewares/swagger.js
  src/models/quiz.js
  src/routes/index.js
  src/routes/quiz.js
  src/services/quiz.js
  src/test/integration/controllers/quiz.spec.js
  src/test/unit/services/quiz.spec.js
  src/validation/services/quiz.js
Labels: Backend, feature, sprint 6

#115 Image Deletion
  src/services/image.js
  src/services/user.js
Labels: Backend, feature, sprint 6

#90 Get subject names based on Category ID
  src/controllers/category.js
  src/routes/category.js
  src/services/category.js
  src/test/integration/controllers/category.spec.js
  src/test/unit/services/category.spec.js
Labels: Backend, feature, sprint 5

#124 fix response status
  src/controllers/confirmEmail.js
  src/services/auth.js
Labels: Backend, bug, sprint 6
