Repository WebUI-Project-Based-07-nr/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#24 Feature/20/add swagger
  package-lock.json
  package.json
  src/docs/schemas/auth/forgot-password.js
  src/docs/schemas/auth/login.js
  src/docs/schemas/auth/reset-password.js
  src/docs/schemas/auth/signup.js
  src/docs/schemas/email/send-email.js
  src/docs/schemas/message/clear-message.js
  src/docs/schemas/message/delete-message.js
  src/docs/schemas/message/get-message.js
  src/docs/schemas/message/send-message.js
  src/docs/schemas/offers/create-offer.js
  src/docs/schemas/offers/delete-offer.js
  src/docs/schemas/offers/get-offer-by-id.js
  src/docs/schemas/offers/get-offers.js
  src/docs/schemas/offers/update-offer.js
  src/docs/schemas/questions/create-question.js
  src/docs/schemas/questions/delete-question.js
  src/docs/schemas/questions/get-question-by-id.js
  src/docs/schemas/questions/get-questions.js
  src/docs/schemas/questions/update-question-by-id.js
  src/docs/schemas/resources/create-resources-category.js
  src/docs/schemas/resources/delete-resources-category.js
  src/docs/schemas/resources/get-resources.js
  src/docs/schemas/resources/update-resources-category.js
  src/docs/schemas/users/change-user-status.js
  src/docs/schemas/users/delete-user-by-id.js
  src/docs/schemas/users/get-users.js
  src/docs/schemas/users/update-user-by-id.js
  src/initialization/initialization.js
  src/middlewares/swagger.js
  src/middlewares/swaggerUI.js
  src/routes/adminInvitation.js
  src/routes/auth.js
  src/routes/email.js
  src/routes/message.js
  src/routes/offer.js
  src/routes/question.js
  src/routes/resourcesCategory.js
  src/routes/user.js
Labels: documentation, enhancement, Backend

#25 SonarCloud Intergration
  .github/workflows/main.yaml
  sonar-project.properties
Labels: Backend, feature

#37 Unit tests for idValidation middleware
  src/test/unit/middlewares/idValidation.spec.js
Labels: Backend, test

#40 Test/30/question service integration
  package-lock.json
  package.json
  src/test/dbHandler.js
  src/test/integration/services/question.spec.js
  src/test/integration/services/user.spec.js
Labels: Backend, sprint 2, test

#41 Integration tests for email service
  src/test/integration/services/email.spec.js
Labels: Backend, test

#39 Test/31/user service integration
  src/test/integration/services/user.spec.js
Labels: Backend, test

#43 Unit tests for validation middleware
  src/test/unit/middlewares/validation.spec.js
Labels: Backend, test

#48 Setup Code Coverage Reporting for SonarCloud
  .github/workflows/main.yaml
  sonar-project.properties
Labels: enhancement, Backend

#49 #15 added default user nativeLanguage
  src/models/user.js
Labels: bug, sprint 2

#53 Integration test for adminInvitation service
  src/test/integration/services/adminInvitation.spec.js
Labels: Backend, test

#63 Fix the spelling
  src/test/integration/controllers/resourcesCategory.spec.js
Labels: Backend

#60 Google OAuth2
  package-lock.json
  package.json
  src/consts/errors.js
  src/controllers/auth.js
  src/routes/auth.js
  src/services/auth.js
  src/test/integration/controllers/auth.spec.js
Labels: enhancement, Backend, test

#65 Location service
  src/configs/config.js
  src/consts/location.js
  src/controllers/location.js
  src/routes/index.js
  src/routes/location.js
  src/services/location.js
  src/test/integration/controllers/location.spec.js
  src/test/unit/services/location.spec.js
Labels: Backend, feature, sprint 3

#64 Email confirmation
  src/consts/errors.js
  src/controllers/confirmEmail.js
  src/routes/confirmEmail.js
  src/routes/index.js
  src/services/confirmEmail.js
  src/test/integration/controllers/confirmEmail.spec.js
  src/test/unit/services/confirmEmail.spec.js
Labels: Backend, feature, sprint 3

#70 Missing curly brace
  src/consts/errors.js
Labels: Backend, bug

#61 Password encryption/decryption
  src/services/auth.js
  src/services/user.js
  src/test/integration/services/user.spec.js
  src/utils/users/passwordEncryption.js
Labels: Backend, feature, sprint 3
